# Generated by Django 5.0.4 on 2024-04-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='suggestions',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
